<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration {
    /**
     * La conexión de base de datos que debe usar la migración.
     */
    protected $connection = 'pgsql_licencias';

    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // 1. Agregar columna coduso
        Schema::connection($this->connection)->table('licencia.tipoestablecimiento', function (Blueprint $table) {
            $table->string('coduso', 10)->nullable()->after('tes_filaeliminada')->comment('Código de uso catastral - Relación con DS_INFOCAT.MACATUSO');
        });

        // 2. Configurar tes_id como IDENTITY (auto-incremental)
        DB::connection($this->connection)->statement('
            ALTER TABLE licencia.tipoestablecimiento 
            ALTER COLUMN tes_id ADD GENERATED BY DEFAULT AS IDENTITY
        ');

        // 3. Resetear la secuencia al valor máximo actual
        DB::connection($this->connection)->statement("
            SELECT setval(
                pg_get_serial_sequence('licencia.tipoestablecimiento', 'tes_id'), 
                COALESCE(MAX(tes_id), 1)
            ) FROM licencia.tipoestablecimiento
        ");

        // 4. Agregar nueva columna TEXT para tes_descripcion
        DB::connection($this->connection)->statement('
            ALTER TABLE licencia.tipoestablecimiento 
            ADD COLUMN tes_descripcion_nueva TEXT
        ');

        // 5. Copiar datos de tes_descripcion a la nueva columna
        DB::connection($this->connection)->statement('
            UPDATE licencia.tipoestablecimiento 
            SET tes_descripcion_nueva = tes_descripcion
        ');

        // 6. Renombrar columnas (vieja a _old, nueva a original)
        DB::connection($this->connection)->statement('
            ALTER TABLE licencia.tipoestablecimiento 
            RENAME COLUMN tes_descripcion TO tes_descripcion_old
        ');

        DB::connection($this->connection)->statement('
            ALTER TABLE licencia.tipoestablecimiento 
            RENAME COLUMN tes_descripcion_nueva TO tes_descripcion
        ');

        // 7. Crear vista con cast a varchar(80) para compatibilidad
        DB::connection($this->connection)->statement("
            CREATE OR REPLACE VIEW licencia.vu_tipoestablecimiento AS
            SELECT 
                tes_id,
                tes_descripcion::varchar(80) AS tes_descripcion, 
                tes_filaoriginal,
                tes_filaeliminada,
                coduso
            FROM licencia.tipoestablecimiento
            WHERE tes_filaeliminada = false
        ");
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Eliminar la vista
        DB::connection($this->connection)->statement('
            DROP VIEW IF EXISTS licencia.vu_tipoestablecimiento
        ');

        // Renombrar columnas de vuelta
        DB::connection($this->connection)->statement('
            ALTER TABLE licencia.tipoestablecimiento 
            RENAME COLUMN tes_descripcion TO tes_descripcion_nueva
        ');

        DB::connection($this->connection)->statement('
            ALTER TABLE licencia.tipoestablecimiento 
            RENAME COLUMN tes_descripcion_old TO tes_descripcion
        ');

        // Eliminar la columna nueva
        DB::connection($this->connection)->statement('
            ALTER TABLE licencia.tipoestablecimiento 
            DROP COLUMN IF EXISTS tes_descripcion_nueva
        ');

        // Eliminar columna coduso
        Schema::connection($this->connection)->table('licencia.tipoestablecimiento', function (Blueprint $table) {
            $table->dropColumn('coduso');
        });
    }
};
